name: Add assets to release
on:
  release:
    types: [created]

jobs:
  release:
    name: Add fabm-plus source code
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Python dependencies
        run: python -m pip install git-archive-all
      - name: Clone fabm-plus
        uses: actions/checkout@v4
        with:
          repository: fabm-model/fabm-plus
          submodules: recursive
          fetch-depth: 0
      - name: Ensure code is in sync with master
        run: |
          git config user.name "Automerge Bot"
          git config user.email "bot@example.com"
          git config pull.rebase false
          git pull ${{ github.repositoryUrl }}
      - name: Archive code including submodules
        run: |
          git-archive-all code.tar.gz
          git-archive-all code.zip
      - name: Upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.ref_name }} code.tar.gz#"Source code including third-party biogeochemical models (tar.gz)"
          gh release upload ${{ github.ref_name }} code.zip#"Source code including third-party biogeochemical models (zip)"
